variables:
  CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astropy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    coverage: codecov

    envs:

    - linux: codestyle

    - macos: py36-test-cov
    - macos: py37-test-cov
    - macos: py38-test-cov
    - macos: py39-test-cov

    - linux: py36-test-cov
    - linux: py37-test-cov
    - linux: py38-test-cov
    - linux: py39-test-cov

    - linux32: py36-test-cov
    - linux32: py37-test-cov
    - linux32: py38-test-cov
    - linux32: py39-test-cov

    - windows: py36-test-cov
    - windows: py37-test-cov
    - windows: py38-test-cov
    - windows: py39-test-cov

    - macos: build_docs
    - linux: build_docs
    - macos: build_docs

- template: publish.yml@OpenAstronomy
  parameters:
    test_command: pytest -p no:warnings --pyargs astropy_healpix
    test_extras: test
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      pypi_connection_name : 'pypi_endpoint'
    targets:
    - sdist
    - wheels_linux
    - wheels_macos
    - wheels_windows
