# Conda environment for astropy-healpix development
#
# Install:    conda env create -f environment-dev.yml
# Update:     conda env update -f environment-dev.yml
# Activate:   conda activate astropy-healpix
# Deactivate: conda deactivate

name: astropy-healpix

channels:
  - conda-forge

dependencies:
  - python==3.9
  - pip
  - ipython
  - numpy
  - astropy
  - scipy
  - matplotlib
  - healpy
  - reproject
  - pytest
  - sphinx
  - pylint
  - flake8
  - hypothesis
  - pip:
    - sphinx-rtd-theme==0.3
    - pydocstyle
