# GitHub Actions workflow for testing Emscripten/WebAssembly build via Pyodide

name: Emscripten

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-wasm:
    name: Build for WebAssembly
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.12'

      - name: Install pyodide-build
        run: pip install pyodide-build>=0.29.2

      - name: Get Emscripten version
        run: echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV

      - name: Set up Emscripten SDK
        uses: mymindstorm/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984  # v16
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}

      - name: Build wheel for Pyodide
        run: pyodide build
