# GitHub Actions workflow for testing Emscripten/WebAssembly build via Pyodide

name: Emscripten

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-wasm:
    name: Build for WebAssembly
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.12'

      - name: Install pyodide-build
        run: pip install pyodide-build>=0.29.2

      - name: Get Emscripten version
        run: echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV

      - name: Set up Emscripten SDK
        uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021  # v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}

      - name: Build wheel for Pyodide
        run: pyodide build
